### ISSUE TITLE
Error head request with “404 Not Found”

### ISSUE THREAD

**Issue by mrmuiz** [mwatz1234/pihole-dot-doh-updatelists#2]
When updating with Watchtower it gives an error:

level=warning msg="Could not do a head request for \"mwatz/pihole-unbound-updatelists:latest\", falling back to regular pull." container=/pihole-unbound image="mwatz/pihole-unbound-updatelists:latest"
level=warning msg="Reason: registry responded to head request with \"404 Not Found\", auth: \"not present\"" container=/pihole-unbound image="mwatz/pihole-unbound-updatelists:latest"

More about this here: https://github.com/containrrr/watchtower/discussions/1529#discussioncomment-4748053
And here: https://github.com/docker/buildx/issues/1509#issuecomment-1378538197

**Comment by mwatz1234** [comment]
Sorry, I haven't been monitoring my github repo's.  Is this still an issue?
I don't use watchtower on my pihole docker images, so I am not aware of this issue.

**Comment by mrmuiz** [comment]
I dont know i switched to another one months ago. Thx for the reply.
